### PR TITLE
Set line & column to 1,1 to avoid a flake8 error

### PR DESCRIPTION
**Pull request by dobesv**
flake8 currently doesn't seem to like an error reported on line `0`.

### CODE REVIEW

**Comment by dobesv** [comment]
See https://github.com/savoirfairelinux/flake8-copyright/issues/3

**Comment by ghost** [comment]
What do you mean by "doesn't like"? I don't see any problem on my machine. Do you have a warning or an error message?

**Comment by ghost** [comment]
Oh, sorry, I didn't even bother looking at the issue, nevermind. Trying to reproduce...

**Comment by ghost** [comment]
I can't seem to be able to reproduce the issue, but since the change is so small and makes sense (line 0 doesn't exist in a file), I'll merge it anyway. Thanks.

**Comment by dobesv** [comment]
Okay, thanks.  I have no idea why you don't see it, maybe some plugin is
triggering it.

**Pull request merged**
